// SPDX-License-Identifier: MIT
pragma solidity ^0.8.34;

import {AccessControlEnumerableStorage} from "@lattice/access/libraries/AccessControlEnumerableLib.sol";
import {AccessControlStorage} from "@lattice/access/libraries/AccessControlLib.sol";
import {AccessControlTimedStorage} from "@lattice/access/libraries/AccessControlTimedLib.sol";
import {AccessManagedStorage} from "@lattice/access/libraries/AccessManagedLib.sol";
import {AccessManagerStorage} from "@lattice/access/libraries/AccessManagerLib.sol";
import {ERC6900ModuleManagerStorage} from "@lattice/accounts/erc6900/libraries/ERC6900ModuleManagerLib.sol";
import {ERC7579ModuleConfigStorage} from "@lattice/accounts/erc7579/libraries/ERC7579ModuleConfigLib.sol";
import {AccountSignerStorage} from "@lattice/accounts/libraries/AccountSignerLib.sol";
import {ERC4337ValidationStorage} from "@lattice/accounts/libraries/ERC4337ValidationLib.sol";
import {ERC6551AccountStorage} from "@lattice/accounts/libraries/ERC6551AccountLib.sol";
import {SessionKeyStorage} from "@lattice/accounts/libraries/SessionKeyLib.sol";
import {ConstantProductStorage} from "@lattice/amm/libraries/ConstantProductLib.sol";
import {AcrossBridgeAdapterStorage} from "@lattice/crosschain/across/AcrossBridgeAdapterLib.sol";
import {AxelarGatewayAdapterStorage} from "@lattice/crosschain/axelar/AxelarGatewayAdapterLib.sol";
import {CCIPGatewayAdapterStorage} from "@lattice/crosschain/chainlink/CCIPGatewayAdapterLib.sol";
import {CCTPBridgeAdapterStorage} from "@lattice/crosschain/circle/CCTPBridgeAdapterLib.sol";
import {HyperbridgeGatewayAdapterStorage} from "@lattice/crosschain/hyperbridge/HyperbridgeGatewayAdapterLib.sol";
import {HyperlaneGatewayAdapterStorage} from "@lattice/crosschain/hyperlane/HyperlaneGatewayAdapterLib.sol";
import {LayerZeroGatewayAdapterStorage} from "@lattice/crosschain/layerzero/LayerZeroGatewayAdapterLib.sol";
import {StargateBridgeAdapterStorage} from "@lattice/crosschain/layerzero/StargateBridgeAdapterLib.sol";
import {BridgeERC20Storage} from "@lattice/crosschain/libraries/BridgeERC20Lib.sol";
import {BridgeERC7802Storage} from "@lattice/crosschain/libraries/BridgeERC7802Lib.sol";
import {ChainRegistryStorage} from "@lattice/crosschain/libraries/ChainRegistryLib.sol";
import {CrosschainLinkStorage} from "@lattice/crosschain/libraries/CrosschainLinkLib.sol";
import {ERC7786OpenBridgeStorage} from "@lattice/crosschain/libraries/ERC7786OpenBridgeLib.sol";
import {
    L1ToL2CrossDomainMessengerGatewayAdapterStorage
} from "@lattice/crosschain/optimism/L1ToL2CrossDomainMessengerGatewayAdapterLib.sol";
import {
    L2ToL2CrossDomainMessengerGatewayAdapterStorage
} from "@lattice/crosschain/optimism/L2ToL2CrossDomainMessengerGatewayAdapterLib.sol";
import {StarknetGatewayAdapterStorage} from "@lattice/crosschain/starknet/StarknetGatewayAdapterLib.sol";
import {WormholeGatewayAdapterStorage} from "@lattice/crosschain/wormhole/WormholeGatewayAdapterLib.sol";
import {ZetaChainGatewayAdapterStorage} from "@lattice/crosschain/zetachain/ZetaChainGatewayAdapterLib.sol";
import {AaveV3AdapterStorage} from "@lattice/defi/libraries/AaveV3AdapterLib.sol";
import {AggregatorExecAdapterStorage} from "@lattice/defi/libraries/AggregatorExecAdapterLib.sol";
import {CompoundV3AdapterStorage} from "@lattice/defi/libraries/CompoundV3AdapterLib.sol";
import {CurveStableSwapAdapterStorage} from "@lattice/defi/libraries/CurveStableSwapAdapterLib.sol";
import {ERC4626AdapterStorage} from "@lattice/defi/libraries/ERC4626AdapterLib.sol";
import {GovernedVaultStorage} from "@lattice/defi/libraries/GovernedVaultLib.sol";
import {LidoAdapterStorage} from "@lattice/defi/libraries/LidoAdapterLib.sol";
import {StrategyManagerStorage} from "@lattice/defi/libraries/StrategyManagerLib.sol";
import {UniswapV3AdapterStorage} from "@lattice/defi/libraries/UniswapV3AdapterLib.sol";
import {VaultCoreStorage} from "@lattice/defi/libraries/VaultCoreLib.sol";
import {ENSResolverStorage} from "@lattice/ens/libraries/ENSResolverLib.sol";
import {ENSReverseClaimerStorage} from "@lattice/ens/libraries/ENSReverseClaimerLib.sol";
import {ENSSubnameIssuerStorage} from "@lattice/ens/libraries/ENSSubnameIssuerLib.sol";
import {GovernedDiamondCutStorage} from "@lattice/governance/libraries/GovernedDiamondCutLib.sol";
import {GovernedSafeDiamondCutStorage} from "@lattice/governance/libraries/GovernedSafeDiamondCutLib.sol";
import {GovernorStorage} from "@lattice/governance/libraries/GovernorLib.sol";
import {SafeDiamondCutStorage} from "@lattice/governance/libraries/SafeDiamondCutLib.sol";
import {SafeHarborAdopterStorage} from "@lattice/governance/libraries/SafeHarborAdopterLib.sol";
import {TimelockControllerStorage} from "@lattice/governance/libraries/TimelockControllerLib.sol";
import {VotesStorage} from "@lattice/governance/libraries/VotesLib.sol";
import {API3AdapterStorage} from "@lattice/oracles/api3/API3AdapterLib.sol";
import {API3QRNGAdapterStorage} from "@lattice/oracles/api3/API3QRNGAdapterLib.sol";
import {BandAdapterStorage} from "@lattice/oracles/band/BandAdapterLib.sol";
import {ChainlinkAdapterStorage} from "@lattice/oracles/chainlink/ChainlinkAdapterLib.sol";
import {ChainlinkAutomationAdapterStorage} from "@lattice/oracles/chainlink/ChainlinkAutomationAdapterLib.sol";
import {ChainlinkCREAdapterStorage} from "@lattice/oracles/chainlink/ChainlinkCREAdapterLib.sol";
import {ChainlinkVRFStorage} from "@lattice/oracles/chainlink/ChainlinkVRFLib.sol";
import {ChronicleAdapterStorage} from "@lattice/oracles/chronicle/ChronicleAdapterLib.sol";
import {DIAAdapterStorage} from "@lattice/oracles/dia/DIAAdapterLib.sol";
import {GelatoAutomateAdapterStorage} from "@lattice/oracles/gelato/GelatoAutomateAdapterLib.sol";
import {GelatoVRFAdapterStorage} from "@lattice/oracles/gelato/GelatoVRFAdapterLib.sol";
import {PythAdapterStorage} from "@lattice/oracles/pyth/PythAdapterLib.sol";
import {PythEntropyAdapterStorage} from "@lattice/oracles/pyth/PythEntropyAdapterLib.sol";
import {RedStoneAdapterStorage} from "@lattice/oracles/redstone/RedStoneAdapterLib.sol";
import {TellorAdapterStorage} from "@lattice/oracles/tellor/TellorAdapterLib.sol";
import {TWAPOracleStorage} from "@lattice/oracles/uniswap/TWAPOracleLib.sol";
import {CommitRevealStorage} from "@lattice/privacy/libraries/CommitRevealLib.sol";
import {ERC6538RegistryStorage} from "@lattice/privacy/libraries/ERC6538RegistryLib.sol";
import {PrivateVotingStorage} from "@lattice/privacy/libraries/PrivateVotingLib.sol";
import {SemaphoreStorage} from "@lattice/privacy/libraries/SemaphoreLib.sol";
import {ShieldedPoolStorage} from "@lattice/privacy/libraries/ShieldedPoolLib.sol";
import {CircuitBreakerStorage} from "@lattice/security/libraries/CircuitBreakerLib.sol";
import {EmergencyStopStorage} from "@lattice/security/libraries/EmergencyStopLib.sol";
import {InvariantCheckerStorage} from "@lattice/security/libraries/InvariantCheckerLib.sol";
import {PausableStorage} from "@lattice/security/libraries/PausableLib.sol";
import {RateLimiterStorage} from "@lattice/security/libraries/RateLimiterLib.sol";
import {ERC1155Storage} from "@lattice/tokens/ERC1155/libraries/ERC1155Lib.sol";
import {ERC20CappedStorage} from "@lattice/tokens/ERC20/libraries/ERC20CappedLib.sol";
import {ERC20Storage} from "@lattice/tokens/ERC20/libraries/ERC20Lib.sol";
import {ERC20WrapperStorage} from "@lattice/tokens/ERC20/libraries/ERC20WrapperLib.sol";
import {ERC2981Storage} from "@lattice/tokens/ERC2981/libraries/ERC2981Lib.sol";
import {ERC4626Storage} from "@lattice/tokens/ERC4626/libraries/ERC4626Lib.sol";
import {ERC721Storage} from "@lattice/tokens/ERC721/libraries/ERC721Lib.sol";
import {ERC721URIStorageStorage} from "@lattice/tokens/ERC721/libraries/ERC721URIStorageLib.sol";
import {MarketplaceZoneStorage} from "@lattice/tokens/libraries/MarketplaceZoneLib.sol";
import {EIP712Storage} from "@lattice/utils/libraries/EIP712Lib.sol";
import {NoncesStorage} from "@lattice/utils/libraries/NoncesLib.sol";
import {VestingWalletStorage} from "@lattice/utils/libraries/VestingWalletLib.sol";

/// @title StorageLayoutProbe
/// @notice Compile-only probe importing the actual source types; never deployed.
contract StorageLayoutProbe {
    AccessControlEnumerableStorage internal s0;
    AccessControlStorage internal s1;
    AccessControlTimedStorage internal s2;
    AccessManagedStorage internal s3;
    AccessManagerStorage internal s4;
    ERC6900ModuleManagerStorage internal s5;
    ERC7579ModuleConfigStorage internal s6;
    AccountSignerStorage internal s7;
    ERC4337ValidationStorage internal s8;
    ERC6551AccountStorage internal s9;
    SessionKeyStorage internal s10;
    ConstantProductStorage internal s11;
    AcrossBridgeAdapterStorage internal s12;
    AxelarGatewayAdapterStorage internal s13;
    CCIPGatewayAdapterStorage internal s14;
    CCTPBridgeAdapterStorage internal s15;
    HyperbridgeGatewayAdapterStorage internal s16;
    HyperlaneGatewayAdapterStorage internal s17;
    LayerZeroGatewayAdapterStorage internal s18;
    StargateBridgeAdapterStorage internal s19;
    BridgeERC20Storage internal s20;
    BridgeERC7802Storage internal s21;
    ChainRegistryStorage internal s22;
    CrosschainLinkStorage internal s23;
    ERC7786OpenBridgeStorage internal s24;
    L1ToL2CrossDomainMessengerGatewayAdapterStorage internal s25;
    L2ToL2CrossDomainMessengerGatewayAdapterStorage internal s26;
    StarknetGatewayAdapterStorage internal s27;
    WormholeGatewayAdapterStorage internal s28;
    ZetaChainGatewayAdapterStorage internal s29;
    AaveV3AdapterStorage internal s30;
    AggregatorExecAdapterStorage internal s31;
    CompoundV3AdapterStorage internal s32;
    CurveStableSwapAdapterStorage internal s33;
    ERC4626AdapterStorage internal s34;
    GovernedVaultStorage internal s35;
    LidoAdapterStorage internal s36;
    StrategyManagerStorage internal s37;
    UniswapV3AdapterStorage internal s38;
    VaultCoreStorage internal s39;
    ENSResolverStorage internal s40;
    ENSReverseClaimerStorage internal s41;
    ENSSubnameIssuerStorage internal s42;
    GovernedDiamondCutStorage internal s43;
    GovernedSafeDiamondCutStorage internal s44;
    GovernorStorage internal s45;
    SafeDiamondCutStorage internal s46;
    SafeHarborAdopterStorage internal s47;
    TimelockControllerStorage internal s48;
    VotesStorage internal s49;
    API3AdapterStorage internal s50;
    API3QRNGAdapterStorage internal s51;
    BandAdapterStorage internal s52;
    ChainlinkAdapterStorage internal s53;
    ChainlinkAutomationAdapterStorage internal s54;
    ChainlinkCREAdapterStorage internal s55;
    ChainlinkVRFStorage internal s56;
    ChronicleAdapterStorage internal s57;
    DIAAdapterStorage internal s58;
    GelatoAutomateAdapterStorage internal s59;
    GelatoVRFAdapterStorage internal s60;
    PythAdapterStorage internal s61;
    PythEntropyAdapterStorage internal s62;
    RedStoneAdapterStorage internal s63;
    TellorAdapterStorage internal s64;
    TWAPOracleStorage internal s65;
    CommitRevealStorage internal s66;
    ERC6538RegistryStorage internal s67;
    PrivateVotingStorage internal s68;
    SemaphoreStorage internal s69;
    ShieldedPoolStorage internal s70;
    CircuitBreakerStorage internal s71;
    EmergencyStopStorage internal s72;
    InvariantCheckerStorage internal s73;
    PausableStorage internal s74;
    RateLimiterStorage internal s75;
    ERC1155Storage internal s76;
    ERC20CappedStorage internal s77;
    ERC20Storage internal s78;
    ERC20WrapperStorage internal s79;
    ERC2981Storage internal s80;
    ERC4626Storage internal s81;
    ERC721Storage internal s82;
    ERC721URIStorageStorage internal s83;
    MarketplaceZoneStorage internal s84;
    EIP712Storage internal s85;
    NoncesStorage internal s86;
    VestingWalletStorage internal s87;
}
