// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

/// @title FacetInventory
/// @author David Dada <daveproxy80@gmail.com> (https://github.com/dadadave80)
/// @notice THE canonical Lattice release inventory: the single (contract name, `"<file>:<Name>"` artifact
///         path) list of every facet that ships in a release. Consumed by BOTH the ERC-8153 parity gate
///         (`test/unit/ExportSelectorsParityTest.t.sol` — every entry must self-report its exact `forge
///         inspect` selector set) and the {DeployRelease} script (every entry is CREATE2-deployed at its
///         deterministic raw-salt address and registered in the {LatticeRegistry}). Adding a facet HERE is
///         what adds it to the release — and simultaneously puts it under the parity gate.
/// @dev Stateless `pure` library so scripts and tests share one source of truth. Names must match the
///      artifact contract names exactly: the registry key is `keccak256("lattice.<name>")` and the facet
///      deploy salt is `keccak256("lattice.<name>.<version>")`, so renaming an entry re-derives BOTH.
library FacetInventory {
    /// @notice The 99 release facets (95 Lattice + 4 diamond-lib core) as (contract name, `"<file>:<Name>"` deploy path) pairs.
    /// @return names The facet contract names (registry name = `"lattice." ++ name`).
    /// @return paths The matching `vm.getCode`/`deployCode` artifact paths, index-aligned with `names`.
    function inventory() internal pure returns (string[] memory names, string[] memory paths) {
        string[99] memory n = [
            "AcrossBridgeAdapter",
            "AxelarGatewayAdapter",
            "BridgeERC20",
            "BridgeERC7802",
            "CCIPGatewayAdapter",
            "CCTPBridgeAdapter",
            "ChainRegistry",
            "CrosschainLink",
            "CrosschainTimelockHandler",
            "ERC7786OpenBridge",
            "HyperbridgeGatewayAdapter",
            "HyperlaneGatewayAdapter",
            "L1ToL2CrossDomainMessengerGatewayAdapter",
            "L2ToL2CrossDomainMessengerGatewayAdapter",
            "LayerZeroGatewayAdapter",
            "StargateBridgeAdapter",
            "StarknetGatewayAdapter",
            "SuperchainETHBridgeAdapter",
            "WormholeGatewayAdapter",
            "ZetaChainGatewayAdapter",
            "API3Adapter",
            "API3QRNGAdapter",
            "BandAdapter",
            "ChainlinkAdapter",
            "ChainlinkAutomationAdapter",
            "ChainlinkCREAdapter",
            "ChainlinkVRF",
            "ChronicleAdapter",
            "DIAAdapter",
            "GelatoAutomateAdapter",
            "GelatoVRFAdapter",
            "PythAdapter",
            "PythEntropyAdapter",
            "RedStoneAdapter",
            "TellorAdapter",
            "TWAPOracle",
            "ERC1155",
            "ERC20",
            "ERC20Burnable",
            "ERC20Capped",
            "ERC20Crosschain",
            "ERC20FlashMint",
            "ERC20Pausable",
            "ERC20Permit",
            "ERC20Votes",
            "ERC2981",
            "ERC4626",
            "ERC721",
            "ERC7802",
            "MarketplaceZone",
            "AccountSigner",
            "ERC1271Signature",
            "ERC4337Validation",
            "ERC6900AccountView",
            "ERC6900Executor",
            "ERC6900ModuleManager",
            "ERC6900Signature",
            "ERC6900Validation",
            "ERC7821Executor",
            "ConstantProduct",
            "AggregatorExecAdapter",
            "GovernedVault",
            "StrategyManager",
            "VaultCore",
            "CommitReveal",
            "ERC5564Announcer",
            "ERC6538Registry",
            "Groth16Verifier",
            "PlonkVerifier",
            "PrivateVoting",
            "Semaphore",
            "ShieldedPool",
            "AccessControlDiamondCut",
            "GovernedDiamondCut",
            "GovernedSafeDiamondCut",
            "Governor",
            "SafeDiamondCut",
            "SafeHarborAdopter",
            "TimelockController",
            "Votes",
            "CircuitBreaker",
            "EmergencyStop",
            "InvariantChecker",
            "Pausable",
            "RateLimiter",
            "AccessControl",
            "AccessControlEnumerable",
            "AccessControlTimed",
            "AccessManaged",
            "AccessManager",
            "ENSResolver",
            "ENSReverseClaimer",
            "ENSSubnameIssuer",
            "EIP712",
            "Multicall",
            // diamond-lib core facets (>=0.2.0 they implement IFacet/ERC-8153, so they are releasable —
            // release-versioned like every entry; the loupe entry is what lets factory recipes satisfy
            // the mandatory loupe coverage straight from the registry)
            "DiamondCutFacet",
            "DiamondLoupeFacet",
            "ERC165Facet",
            "OwnableFacet"
        ];
        string[99] memory p = [
            "src/crosschain/across/AcrossBridgeAdapter.sol:AcrossBridgeAdapter",
            "src/crosschain/axelar/AxelarGatewayAdapter.sol:AxelarGatewayAdapter",
            "src/crosschain/BridgeERC20.sol:BridgeERC20",
            "src/crosschain/BridgeERC7802.sol:BridgeERC7802",
            "src/crosschain/chainlink/CCIPGatewayAdapter.sol:CCIPGatewayAdapter",
            "src/crosschain/circle/CCTPBridgeAdapter.sol:CCTPBridgeAdapter",
            "src/crosschain/ChainRegistry.sol:ChainRegistry",
            "src/crosschain/CrosschainLink.sol:CrosschainLink",
            "src/crosschain/CrosschainTimelockHandler.sol:CrosschainTimelockHandler",
            "src/crosschain/ERC7786OpenBridge.sol:ERC7786OpenBridge",
            "src/crosschain/hyperbridge/HyperbridgeGatewayAdapter.sol:HyperbridgeGatewayAdapter",
            "src/crosschain/hyperlane/HyperlaneGatewayAdapter.sol:HyperlaneGatewayAdapter",
            "src/crosschain/optimism/L1ToL2CrossDomainMessengerGatewayAdapter.sol:L1ToL2CrossDomainMessengerGatewayAdapter",
            "src/crosschain/optimism/L2ToL2CrossDomainMessengerGatewayAdapter.sol:L2ToL2CrossDomainMessengerGatewayAdapter",
            "src/crosschain/layerzero/LayerZeroGatewayAdapter.sol:LayerZeroGatewayAdapter",
            "src/crosschain/layerzero/StargateBridgeAdapter.sol:StargateBridgeAdapter",
            "src/crosschain/starknet/StarknetGatewayAdapter.sol:StarknetGatewayAdapter",
            "src/crosschain/optimism/SuperchainETHBridgeAdapter.sol:SuperchainETHBridgeAdapter",
            "src/crosschain/wormhole/WormholeGatewayAdapter.sol:WormholeGatewayAdapter",
            "src/crosschain/zetachain/ZetaChainGatewayAdapter.sol:ZetaChainGatewayAdapter",
            "src/oracles/api3/API3Adapter.sol:API3Adapter",
            "src/oracles/api3/API3QRNGAdapter.sol:API3QRNGAdapter",
            "src/oracles/band/BandAdapter.sol:BandAdapter",
            "src/oracles/chainlink/ChainlinkAdapter.sol:ChainlinkAdapter",
            "src/oracles/chainlink/ChainlinkAutomationAdapter.sol:ChainlinkAutomationAdapter",
            "src/oracles/chainlink/ChainlinkCREAdapter.sol:ChainlinkCREAdapter",
            "src/oracles/chainlink/ChainlinkVRF.sol:ChainlinkVRF",
            "src/oracles/chronicle/ChronicleAdapter.sol:ChronicleAdapter",
            "src/oracles/dia/DIAAdapter.sol:DIAAdapter",
            "src/oracles/gelato/GelatoAutomateAdapter.sol:GelatoAutomateAdapter",
            "src/oracles/gelato/GelatoVRFAdapter.sol:GelatoVRFAdapter",
            "src/oracles/pyth/PythAdapter.sol:PythAdapter",
            "src/oracles/pyth/PythEntropyAdapter.sol:PythEntropyAdapter",
            "src/oracles/redstone/RedStoneAdapter.sol:RedStoneAdapter",
            "src/oracles/tellor/TellorAdapter.sol:TellorAdapter",
            "src/oracles/uniswap/TWAPOracle.sol:TWAPOracle",
            "src/tokens/ERC1155/ERC1155.sol:ERC1155",
            "src/tokens/ERC20/ERC20.sol:ERC20",
            "src/tokens/ERC20/ERC20Burnable.sol:ERC20Burnable",
            "src/tokens/ERC20/ERC20Capped.sol:ERC20Capped",
            "src/tokens/ERC20/ERC20Crosschain.sol:ERC20Crosschain",
            "src/tokens/ERC20/ERC20FlashMint.sol:ERC20FlashMint",
            "src/tokens/ERC20/ERC20Pausable.sol:ERC20Pausable",
            "src/tokens/ERC20/ERC20Permit.sol:ERC20Permit",
            "src/tokens/ERC20/ERC20Votes.sol:ERC20Votes",
            "src/tokens/ERC2981/ERC2981.sol:ERC2981",
            "src/tokens/ERC4626/ERC4626.sol:ERC4626",
            "src/tokens/ERC721/ERC721.sol:ERC721",
            "src/tokens/ERC7802/ERC7802.sol:ERC7802",
            "src/tokens/MarketplaceZone.sol:MarketplaceZone",
            "src/accounts/erc7579/AccountSigner.sol:AccountSigner",
            "src/accounts/ERC1271Signature.sol:ERC1271Signature",
            "src/accounts/ERC4337Validation.sol:ERC4337Validation",
            "src/accounts/erc6900/ERC6900AccountView.sol:ERC6900AccountView",
            "src/accounts/erc6900/ERC6900Executor.sol:ERC6900Executor",
            "src/accounts/erc6900/ERC6900ModuleManager.sol:ERC6900ModuleManager",
            "src/accounts/erc6900/ERC6900Signature.sol:ERC6900Signature",
            "src/accounts/erc6900/ERC6900Validation.sol:ERC6900Validation",
            "src/accounts/erc7579/ERC7821Executor.sol:ERC7821Executor",
            "src/amm/ConstantProduct.sol:ConstantProduct",
            "src/defi/AggregatorExecAdapter.sol:AggregatorExecAdapter",
            "src/defi/GovernedVault.sol:GovernedVault",
            "src/defi/StrategyManager.sol:StrategyManager",
            "src/defi/VaultCore.sol:VaultCore",
            "src/privacy/CommitReveal.sol:CommitReveal",
            "src/privacy/ERC5564Announcer.sol:ERC5564Announcer",
            "src/privacy/ERC6538Registry.sol:ERC6538Registry",
            "src/privacy/Groth16Verifier.sol:Groth16Verifier",
            "src/privacy/PlonkVerifier.sol:PlonkVerifier",
            "src/privacy/PrivateVoting.sol:PrivateVoting",
            "src/privacy/Semaphore.sol:Semaphore",
            "src/privacy/ShieldedPool.sol:ShieldedPool",
            "src/governance/AccessControlDiamondCut.sol:AccessControlDiamondCut",
            "src/governance/GovernedDiamondCut.sol:GovernedDiamondCut",
            "src/governance/GovernedSafeDiamondCut.sol:GovernedSafeDiamondCut",
            "src/governance/Governor.sol:Governor",
            "src/governance/SafeDiamondCut.sol:SafeDiamondCut",
            "src/governance/SafeHarborAdopter.sol:SafeHarborAdopter",
            "src/governance/TimelockController.sol:TimelockController",
            "src/governance/Votes.sol:Votes",
            "src/security/CircuitBreaker.sol:CircuitBreaker",
            "src/security/EmergencyStop.sol:EmergencyStop",
            "src/security/InvariantChecker.sol:InvariantChecker",
            "src/security/Pausable.sol:Pausable",
            "src/security/RateLimiter.sol:RateLimiter",
            "src/access/AccessControl.sol:AccessControl",
            "src/access/AccessControlEnumerable.sol:AccessControlEnumerable",
            "src/access/AccessControlTimed.sol:AccessControlTimed",
            "src/access/AccessManaged.sol:AccessManaged",
            "src/access/AccessManager.sol:AccessManager",
            "src/ens/ENSResolver.sol:ENSResolver",
            "src/ens/ENSReverseClaimer.sol:ENSReverseClaimer",
            "src/ens/ENSSubnameIssuer.sol:ENSSubnameIssuer",
            "src/utils/EIP712.sol:EIP712",
            "src/utils/Multicall.sol:Multicall",
            // basename identifiers: lib sources compile to out/<File>.sol/<Name>.json, so the
            // dir-qualified "lib/..." form does not resolve for vm.getCode/deployCode.
            "DiamondCutFacet.sol:DiamondCutFacet",
            "DiamondLoupeFacet.sol:DiamondLoupeFacet",
            "ERC165Facet.sol:ERC165Facet",
            "OwnableFacet.sol:OwnableFacet"
        ];
        names = new string[](99);
        paths = new string[](99);
        for (uint256 i; i < 99; ++i) {
            names[i] = n[i];
            paths[i] = p[i];
        }
    }
}
